spring:
  application:
    name: Spring-Session-Servlet1
  redis:
    #redis单机配置
    host: 192.168.1.88
    port: 6379
    # 选择redis的数据库的分库
    database: 5
    #redis连接池配置
    jedis:
      pool:
        max-idle: 10
        min-idle: 5
        max-active: 100
        max-wait: 3000
        timeout: 6005

server:
  port: 8081

